services:
  app-feat-auth:
    build: .
    container_name: app-feat-auth
    ports:
      - 3001:3000
    environment:
      PORT: 3000
      BRANCH_NAME: feat/auth
    restart: unless-stopped

  app-feat-profile:
    build: .
    container_name: app-feat-profile
    ports:
      - 3002:3000
    environment:
      PORT: 3000
      BRANCH_NAME: feat/profile
    restart: unless-stopped

  app-feat-payment:
    build: .
    container_name: app-feat-payment
    ports:
      - 3003:3000
    environment:
      PORT: 3000
      BRANCH_NAME: feat/payment
    restart: unless-stopped
