name: CI/CD Multi-Branch Docker

on:
  push:
    branches:
      - main
      - feat/auth
      - feat/payment
      - feat/profile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: my-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node
      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: yarn install

      # 4️⃣ Build TypeScript
      - name: Build app
        run: yarn build

      # 5️⃣ Log in to Docker (GHCR example)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with: 
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
      

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: | 
        docker build -t $REGISTRY/${{ github.repository}}/$IMAGE_NAME:${{ github.ref_name }} .

      # 7️⃣ Push Docker image
      - name: Push Docker image
        run: | 
        docker push $REGISTRY/${{ github.repository }}/$IMAGE_NAME:${{ github.ref_name }} 
        


      